ip_sla:
  table_name: "rt2"
  table_id: 200
  policy_rule_priority: 1000

  gw_primary: "177.53.17.71"
  gw_backup:  "177.53.17.69"

  min_ok: 5
  subnet_cidr: "177.53.17.0/24"

  timer_every: "30s"   # 30 em 30 segundos
