ip_sla:
  table_name: "rt2"
  table_id: 200
  policy_rule_priority: 1000

  gw_primary: "177.53.17.71"
  gw_backup:  "177.53.17.69"

  tracked_dests:
    - 10.11.12.6
    - 10.11.10.44
    - 10.21.2.6
    - 10.21.3.24
    - 10.41.2.6
    - 10.41.2.8
    - 10.11.11.42
    - 10.21.3.25
    - 10.11.8.124
    - 10.11.9.150

  min_ok: 1
  subnet_cidr: "177.53.17.0/24"
  timer_every: "30s"
